### ISSUE TITLE
Add ability to download Jekyll themes and PSD files

### ISSUE THREAD

**Issue by ahirschberg** [briancurt/pixelarity-download#4]
Some Pixelarity templates offer Jekyll themes, and all offer PSD files. The script would be more useful if command line flags were exposed to allow for downloading these files as well.

**Comment by alejandroandreu** [comment]
Hi @ahirschberg , please see pull request #6 , or check out my fork. I also needed this and now it's working.

**Comment by briancurt** [comment]
Thanks. Merged #6
