### ISSUE TITLE
ImportError: cannot import name 'cached_property' from 'werkzeug'

### ISSUE THREAD

**Issue by beaufour** [briancurt/pixelarity-download#7]
Thanks for creating this little tool!

After doing `pip install` I'm getting this error when running it from the repo:

```
Traceback (most recent call last):
  File "src/pixelarity-download.py", line 6, in <module>
    from robobrowser import RoboBrowser
  File "/Users/allan/repos/pixelarity-download/.venv/lib/python3.7/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/Users/allan/repos/pixelarity-download/.venv/lib/python3.7/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/Users/allan/repos/pixelarity-download/.venv/lib/python3.7/site-packages/werkzeug/__init__.py)
```

This is on Mac OS 10.15.3 with Python 3.7.7

**Comment by beaufour** [comment]
This one I assume: https://github.com/jmcarp/robobrowser/issues/93

**Comment by manishmaharjan** [comment]
I had a similar issue. 

`import werkzeug
werkzeug.cached_property = werkzeug.utils.cached_property`

adding this before `import robobrowser `solved the issue for me

**Comment by briancurt** [comment]
@beaufour I have read a bit about this and @manishmaharjan workaround apparently is still the "solution". I have updated the script. Thanks both.
